# Generated by Django 4.2.2 on 2023-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador de cada estado que puede tener un bus')),
                ('descripcion', models.CharField(max_length=30, unique=True, verbose_name='Tipo de estado que puede tener un bus')),
            ],
        ),
    ]
