# Generated by Django 4.2.2 on 2023-10-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizacion_buses_cargadores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadobus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de cada estado que puede tener un bus'),
        ),
    ]
