# Generated by Django 4.2.2 on 2023-10-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizacion_buses_cargadores_app', '0003_bus_cargador_estadocargador_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialutilizacioncargadorhora',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizacion_buses_cargadores_app.bus'),
        ),
        migrations.AlterModelTable(
            name='bus',
            table='buses',
        ),
        migrations.AlterModelTable(
            name='cargador',
            table='cargadores',
        ),
        migrations.AlterModelTable(
            name='estadobus',
            table='estados_buses',
        ),
        migrations.AlterModelTable(
            name='estadocargador',
            table='estados_cargadores',
        ),
        migrations.AlterModelTable(
            name='historialutilizacionbushora',
            table='historial_utilizacion_buses_hora',
        ),
        migrations.AlterModelTable(
            name='historialutilizacioncargadorhora',
            table='historial_utilizacion_cargadores_hora',
        ),
        migrations.AlterModelTable(
            name='hora',
            table='horas',
        ),
        migrations.DeleteModel(
            name='UtilizacionCargadorBus',
        ),
    ]
