# Generated by Django 4.2.2 on 2023-10-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizacion_buses_cargadores_app', '0004_historialutilizacioncargadorhora_bus_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='estado_id',
            new_name='estado',
        ),
    ]
